import { awscdk, TextFile } from "projen";

const project = new awscdk.AwsCdkConstructLibrary({
  name: "waf-http-api",
  packageName: "waf-http-api",
  majorVersion: 2,
  description:
    "A CDK construct that fronts an HTTP API with a CloudFront distribution and protects it with AWS WAF.",
  keywords: [
    "awscdk",
    "aws",
    "cdk",
    "api-gateway",
    "http-api",
    "waf",
    "cloudfront",
  ],
  author: "Jaap Haitsma",
  authorAddress: "jaap@haitsma.org",
  copyrightOwner: "Merapar Technologies Group B.V.",
  license: "MIT",
  cdkVersion: "2.200.2",
  // Pin the constructs floor to what v1 published. projen 0.101 wants constructs ^10.5.0
  // for its own use, and letting that leak into peerDependencies would break every
  // consumer pinned below 10.5.1 - including this repo's own example.
  constructsVersion: "10.0.5",
  defaultReleaseBranch: "main",
  jsiiVersion: "~6.0.0",
  // Match the TypeScript that jsii itself compiles with (it pins ~6.0), so the dev-time
  // compiler and the one producing the published output agree.
  typescriptVersion: "~6.0.0",
  jest: true,
  projenrcTs: true,
  repositoryUrl: "https://github.com/JaapHaitsma/waf-http-api.git",
  // Weekly dependency upgrade PRs. This was disabled, which is how jsii drifted onto an
  // End-of-Support release line without anything flagging it.
  depsUpgradeOptions: {
    workflowOptions: {
      schedule: { cron: ["0 4 * * 1"] }, // Mondays, 04:00 UTC
    },
  },

  gitignore: [".vscode", ".DS_Store"],

  releaseToNpm: true,
  // Publish to npm via OIDC trusted publishing rather than a long-lived token.
  // Configured on npmjs.com for this repo; projen drops NPM_TOKEN from the workflow,
  // which matters because npm prefers a token over OIDC when both are present.
  npmTrustedPublishing: true,
  prettier: true,

  publishToPypi: {
    distName: "waf-http-api", // PyPI package name
    module: "waf_http_api", // Python import path
  },
});

project.addDevDeps("husky", "lint-staged");

project.package.addField("lint-staged", {
  "*.{js,ts,json,md}": ["prettier --write", "eslint --fix"],
});

project.package.addField("scripts", {
  prepare: "husky install",
});

new TextFile(project, ".husky/pre-commit", {
  executable: true,
  lines: ["ESLINT_USE_FLAT_CONFIG=false npx lint-staged"],
});

// Get all managed files from project.files
const managedFiles: string[] = Array.from(project.files.values()).map(
  (f) => f.path,
);

// Generated files must never be prettier-formatted. The husky pre-commit hook runs prettier
// over *.json and *.md, which reformats what projen and jsii-docgen emit; CI then regenerates
// them raw, sees a diff, and fails the build's self-mutation check. Keep prettier off them.
managedFiles.forEach((f) => project.prettier?.addIgnorePattern(f));
project.prettier?.addIgnorePattern("API.md"); // generated by jsii-docgen
project.prettier?.addIgnorePattern("example/");

new TextFile(project, ".eslintignore", {
  lines: [
    '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen"',
    ...managedFiles,
    "example/",
    "*.md",
  ],
});

// The examples are standalone CDK apps for readers of this repo, not part of the library.
// Without this they are packed into the npm tarball - example/typescript/package-lock.json
// alone was 156kB of a 160kB package.
project.npmignore?.addPatterns("/example/");

// Ensure the root tsconfig files do not apply to example/*
project.tsconfig?.addExclude("example/**");
project.tsconfigDev?.addExclude("example/**");

project.synth();
